version: '2'
services:
  artifactory_mysql:
    build:
      context: ./artifactory
      dockerfile: Dockerfile
    ports:
        - '8081:8081'
    env_file:
      - ./artifactory/common.env
    environment:
      - DB_TYPE=mysql
    links:
      - mysql
    depends_on:
      - mysql
    command: "bash /usr/bin/run.sh"
    container_name: artifactory_mysql_container
  artifactory_oracle:
    build:
      context: ./artifactory
      dockerfile: Dockerfile
    ports:
        - '8082:8081'
    env_file:
      - ./artifactory/common.env
    environment:
      - DB_TYPE=oracle
    links:
      - oracle
    depends_on:
      - oracle
    command: "bash /usr/bin/run.sh"
    container_name: artifactory_oracle_container
  artifactory_postgres:
    build:
      context: ./artifactory
      dockerfile: Dockerfile
    ports:
      - '8083:8081'
    env_file:
      - ./artifactory/common.env
    environment:
      - DB_TYPE=postgresql
    links:
      - postgresql
    depends_on:
      - postgresql
    command: "bash /usr/bin/run.sh"
    container_name: artifactory_postgresql_container
  mysql:
    build:
      context: ./mysql
      dockerfile: Dockerfile
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - STARTUP_SQL=/tmp/create_db_mysql.sql
    expose:
      - 3306
    container_name: mysql_db_container
  oracle:
    build:
      context: ./oracle
      dockerfile: Dockerfile
    expose:
      - 22
      - 1521
      - 8080
    container_name: oracle_db_container
  postgresql:
    image: postgres:latest
    environment:
      - POSTGRES_USER=artifactory
      - POSTGRES_PASS=password
      - POSTGRES_DATA_DIR=/data
      - POSTGRES_DB=artifactory
    container_name: postgresql_db_container

