version: '2'
services:
  artifactory:
    build:
      context: ./artifactory
      dockerfile: Dockerfile
    ports:
        - '8081:8081'
    environment:
      - ARTIFACTORY_USER=*********
      - ARTIFACTORY_PASSWORD=*********
      - ARTIFACTORY_VERSION=*********
      - ARTIFACTORY_HOME=/var/opt/jfrog/artifactory
      #SPECIFY DB HERE
      - DB_TYPE=*********
      - LIC_URL=*********
#    links:
#      - db
#    depends_on:
#      - db
    command: "bash /usr/bin/run.sh"
    container_name: artifactory1_container

#************************************************************************************************
#********************* MYSQL ********************************************************************
#************************************************************************************************

#  mysql_db:
#    build:
#      context: ./mysql
#      dockerfile: Dockerfile
#    environment:
#      - MYSQL_ROOT_PASSWORD=password
#      - STARTUP_SQL=/tmp/create_db_mysql.sql
#    expose:
#      - 3306
#    container_name: mysql_db_container

#************************************************************************************************
#********************* ORACLE *******************************************************************
#************************************************************************************************

#  oracle_db:
#    build:
#      context: ./oracle
#      dockerfile: Dockerfile
#    expose:
#      - 22
#      - 1521
#      - 8080
#    container_name: oracle_db_container

#************************************************************************************************
#********************* POSTGRES *****************************************************************
#************************************************************************************************

#  postgresql_db:
#    build:
#      context: ./postgresql
#      dockerfile: Dockerfile
#    environment:
#      - POSTGRES_USER=artifactory
#      - POSTGRES_PASSWORD=password
#      - POSTGRES_DB=artifactory
#    expose:
#      - 5432
#    container_name: postgresql_db_container