FROM java

MAINTAINER Daniel Keler <danielk@jfrog.com>

RUN apt-get update && apt-get install -y curl net-tools && \
    curl -u$ARTIFACTORY_USER:$ARTIFACTORY_PASSWORD -o /tmp/jfrog-artifactory-pro-$ARTIFACTORY_VERSION.deb \
    https://repo.artifactoryonline.com/artifactory/libs-releases-local/org/artifactory/pro/deb/jfrog-artifactory-pro/$ARTIFACTORY_VERSION/jfrog-artifactory-pro-$ARTIFACTORY_VERSION.deb && \
    dpkg -i /tmp/jfrog-artifactory-pro-$ARTIFACTORY_VERSION.deb

ADD run.sh /usr/bin/run.sh

RUN chmod +x /usr/bin/run.sh

WORKDIR /usr/bin/

EXPOSE 8081

CMD ["./usr/bin/run.sh"]