version: '2'
services:
  artifactory:
    build:
      context: ../artifactory
      dockerfile: Dockerfile
    ports:
        - '8081:8081'
    env_file:
      - ../artifactory/common.env
    environment:
      - DB_TYPE=mysql
    links:
      - mysql
    depends_on:
      - mysql
    command: "bash /usr/bin/run.sh"
    container_name: artifactory_container
  mysql:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - STARTUP_SQL=/tmp/create_db_mysql.sql
    expose:
      - 3306
    container_name: mysql_db_container